<template>
  <div class="paper-report-view">
    <AgentMessageDock
      :simulation-id="simulationId"
      platform="reddit"
      :visible="!!simulationId"
    />
    <div class="header">
      <button class="back-btn" @click="goBack">
        <i class="fas fa-arrow-left"></i> Back to Dashboard
      </button>
      <h2>IEEE-Style Research Paper</h2>
      <div v-if="loading" class="generating-badge">
        <i class="fas fa-sync fa-spin"></i> Generating Report...
      </div>
    </div>

    <div class="report-content" v-if="reportData && reportData.status === 'completed'">
      <div class="paper-header">
        <h1 class="paper-title">{{ paperTitle }}</h1>
        <div class="paper-meta">
          <span>Simulation ID: {{ simulationId }}</span>
          <span>Type: IEEE-style paper</span>
          <span v-if="reportData.created_at">Generated: {{ formatDate(reportData.created_at) }}</span>
        </div>
        <div class="paper-abstract" v-if="paperAbstract">
          <div class="abstract-label">Abstract</div>
          <p>{{ paperAbstract }}</p>
        </div>
      </div>
      
      <div class="paper-body">
        <!-- We use a custom render method to handle [[Insight: csi_claim_xyz]] tags -->
        <div class="markdown-body" ref="markdownBody"></div>
      </div>
    </div>
    
    <div class="loading-state" v-else-if="loading || (reportData && reportData.status === 'generating')">
      <div class="spinner-container">
        <i class="fas fa-circle-notch fa-spin fa-3x"></i>
      </div>
      <h3>Consulting Cognitive Swarm...</h3>
      <p>Drafting IEEE-style technical paper.</p>
    </div>
    
    <div class="error-state" v-else-if="error">
      <i class="fas fa-exclamation-triangle fa-3x"></i>
      <h3>Error Generating Report</h3>
      <p>{{ error }}</p>
      <button class="retry-btn" @click="generateReport">Try Again</button>
    </div>
    
    <div class="empty-state" v-else>
      <i class="fas fa-file-alt fa-3x"></i>
      <h3>No Report Found</h3>
      <p>Click generate to create a new IEEE-style paper for this simulation run.</p>
      <button class="primary-btn" @click="generateReport">Generate IEEE Paper</button>
    </div>
  </div>
</template>

<script>
import { createApp, h } from 'vue';
import DOMPurify from 'dompurify';
import { marked } from 'marked';
import InsightPopover from '../components/InsightPopover.vue';
import AgentMessageDock from '../components/ui/AgentMessageDock.vue';
import api from '../api';

export default {
  name: 'PaperReportView',
  components: {
    AgentMessageDock
  },
  props: {
    simulationId: {
      type: String,
      required: true
    }
  },
  data() {
    return {
      reportId: null,
      loading: false,
      reportData: null,
      error: null,
      pollInterval: null,
      popoverApps: []
    }
  },
  computed: {
    paperTitle() {
      return this.reportData?.outline?.title || this.reportData?.title || 'IEEE-Style Research Paper'
    },
    paperAbstract() {
      return this.reportData?.outline?.summary || ''
    }
  },
  created() {
    this.fetchReportStatus();
  },
  beforeUnmount() {
    this.stopPolling();
    this.cleanupPopovers();
  },
  methods: {
    goBack() {
      this.$router.push('/');
    },
    formatDate(dateString) {
      if (!dateString) return '';
      return new Date(dateString).toLocaleString();
    },
    async generateReport() {
      this.loading = true;
      this.error = null;
      try {
        const response = await api.post('/api/paper-report/generate', {
          simulation_id: this.simulationId,
          graph_id: '', // Add graph id if we have it in scope
          simulation_requirement: 'Comprehensive Analysis'
        });
        
        if (response && response.report_id) {
          this.reportId = response.report_id;
        }
        
        this.fetchReportStatus();
        this.startPolling();
      } catch (err) {
        console.error("Failed to generate paper report:", err);
        this.error = "Could not initialize report generation.";
        this.loading = false;
      }
    },
    async fetchReportStatus() {
      try {
        // If we already have a report ID generated by PaperReportView
        if (this.reportId) {
          const response = await api.get(`/api/report/${this.reportId}`);
          if (response && response.data) {
            this.handleReportResponse(response.data);
          }
          return;
        }
        
        // Otherwise, first look up if a report already exists for this simulation
        const lookup = await api.get(`/api/paper-report/by-simulation/${this.simulationId}`);
        if (lookup && lookup.data) {
          this.reportId = lookup.data.report_id;
          this.handleReportResponse(lookup.data);
        } else {
          this.reportData = null;
          this.loading = false;
        }
      } catch (err) {
        if (err.response && err.response.status === 404) {
          // Report doesn't exist yet
          this.reportData = null;
        } else {
          console.error("Error fetching report:", err);
          this.error = "Could not fetch report data.";
        }
        this.loading = false;
      }
    },
    handleReportResponse(report) {
      if (!report) return;
      this.reportData = report;
      
      const status = this.reportData.status;
      if (status === 'completed') {
        this.loading = false;
        this.stopPolling();
        
        let reportContent = this.reportData.markdown_content || this.reportData.content || '';
        if (!reportContent && this.reportData.outline && this.reportData.outline.sections) {
          reportContent = this.reportData.outline.sections
            .map(section => `## ${section.title}\n\n${section.content || ''}`.trim())
            .join('\n\n');
        }
        if (!reportContent && this.reportData.sections) {
          reportContent = this.reportData.sections
            .map(section => section.content || section)
            .join('\n\n');
        }
        
        this.$nextTick(() => {
          this.renderMarkdownWithInsights(reportContent);
        });
      } else if (status === 'generating') {
        this.loading = true;
        this.startPolling();
      } else if (status === 'failed') {
        this.loading = false;
        this.error = "Report generation failed on the server.";
        this.stopPolling();
      }
    },
    startPolling() {
      if (!this.pollInterval) {
        this.pollInterval = setInterval(this.fetchReportStatus, 5000);
      }
    },
    stopPolling() {
      if (this.pollInterval) {
        clearInterval(this.pollInterval);
        this.pollInterval = null;
      }
    },
    cleanupPopovers() {
      // Unmount any mounted vue apps for the popovers
      this.popoverApps.forEach(app => app.unmount());
      this.popoverApps = [];
    },
    renderMarkdownWithInsights(markdownText) {
      if (!this.$refs.markdownBody || !markdownText) return;
      
      this.cleanupPopovers();
      
      // Parse standard markdown
      let htmlContent = marked.parse(markdownText);
      
      // Regex to find [[Insight: claim_id]] pattern
      // Uses a UUID or standard ID matching
      const insightRegex = /\[\[Insight:\s*([a-zA-Z0-9_-]+)\]\]/g;
      
      // Replace with placeholder spans
      htmlContent = htmlContent.replace(insightRegex, (match, claimId) => {
        return `<span class="insight-mount-point" data-claim-id="${claimId}"></span>`;
      });
      
      // Inject into DOM
      this.$refs.markdownBody.innerHTML = DOMPurify.sanitize(htmlContent);
      
      // Mount the Vue components onto the placeholders
      this.$nextTick(() => {
        const mountPoints = this.$refs.markdownBody.querySelectorAll('.insight-mount-point');
        
        mountPoints.forEach(el => {
          const claimId = el.getAttribute('data-claim-id');
          
          // Create a new Vue app instance for each popover
          const app = createApp({
            render: () => h(InsightPopover, { 
              claimId: claimId,
              simulationId: this.simulationId
            })
          });
          
          // Mount it
          app.mount(el);
          this.popoverApps.push(app);
        });
      });
    }
  }
}
</script>

<style scoped>
.paper-report-view {
  max-width: 900px;
  margin: 0 auto;
  padding: 40px 20px;
  min-height: 100vh;
  background-color: #fcfcfc;
}

.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 40px;
  border-bottom: 1px solid #eaeaea;
  padding-bottom: 20px;
}

.back-btn {
  background: none;
  border: none;
  color: #666;
  font-size: 1rem;
  cursor: pointer;
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 16px;
  border-radius: 4px;
  transition: all 0.2s;
}

.back-btn:hover {
  background: #f0f0f0;
  color: #333;
}

h2 {
  font-family: "Georgia", serif;
  margin: 0;
  color: #2c3e50;
  font-weight: 400;
}

.generating-badge {
  background: #e3f2fd;
  color: #1976d2;
  padding: 6px 12px;
  border-radius: 20px;
  font-size: 0.85rem;
  font-weight: 500;
}

/* Paper Styling - mimicking Substack/Medium/Academic */
.report-content {
  background: #ffffff;
  padding: 50px 60px;
  border-radius: 8px;
  box-shadow: 0 4px 30px rgba(0,0,0,0.05);
  margin-bottom: 60px;
}

.paper-header {
  margin-bottom: 40px;
  text-align: center;
  border-bottom: 2px solid #2c3e50;
  padding-bottom: 30px;
}

.paper-title {
  font-family: "Georgia", serif;
  font-size: 2.4rem;
  color: #2c3e50;
  margin-bottom: 15px;
  line-height: 1.2;
}

.paper-meta {
  color: #7f8c8d;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  font-size: 0.9rem;
  display: flex;
  justify-content: center;
  gap: 20px;
  flex-wrap: wrap;
  margin-bottom: 20px;
}

.paper-abstract {
  text-align: left;
  max-width: 720px;
  margin: 0 auto;
  background: #f8fafc;
  border: 1px solid #e5e7eb;
  border-left: 4px solid #2c3e50;
  border-radius: 10px;
  padding: 18px 20px;
}

.abstract-label {
  text-transform: uppercase;
  letter-spacing: 0.08em;
  font-size: 0.78rem;
  font-weight: 700;
  color: #334155;
  margin-bottom: 8px;
}

.paper-abstract p {
  margin: 0;
  font-size: 1rem;
  line-height: 1.7;
  color: #334155;
}

.paper-body {
  font-family: "Georgia", serif;
  font-size: 1.15rem;
  line-height: 1.8;
  color: #333;
}

/* Markdown specific styling overrides */
:deep(.markdown-body) h1,
:deep(.markdown-body) h2,
:deep(.markdown-body) h3 {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  color: #2c3e50;
  margin-top: 2em;
  margin-bottom: 0.8em;
  font-weight: 600;
}

:deep(.markdown-body) h1 { font-size: 2.2rem; }
:deep(.markdown-body) h2 { font-size: 1.8rem; border-bottom: 1px solid #eaeaea; padding-bottom: 0.3em; }
:deep(.markdown-body) h3 { font-size: 1.4rem; }

:deep(.markdown-body) p {
  margin-bottom: 1.5em;
}

:deep(.markdown-body) blockquote {
  border-left: 4px solid #bdc3c7;
  padding-left: 20px;
  color: #7f8c8d;
  font-style: italic;
  margin-left: 0;
  margin-right: 0;
}

:deep(.markdown-body) ul, :deep(.markdown-body) ol {
  margin-bottom: 1.5em;
  padding-left: 25px;
}

:deep(.markdown-body) li {
  margin-bottom: 0.5em;
}

/* State views */
.loading-state, .error-state, .empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 80px 20px;
  text-align: center;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 10px rgba(0,0,0,0.05);
}

.spinner-container {
  color: #3498db;
  margin-bottom: 20px;
}

h3 {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  color: #2c3e50;
  margin-bottom: 10px;
}

.error-state i {
  color: #e74c3c;
  margin-bottom: 20px;
}

.empty-state i {
  color: #95a5a6;
  margin-bottom: 20px;
}

p {
  color: #7f8c8d;
  margin-bottom: 25px;
}

button {
  font-family: inherit;
}

.primary-btn, .retry-btn {
  padding: 12px 24px;
  background-color: #2c3e50;
  color: white;
  border: none;
  border-radius: 6px;
  font-size: 1rem;
  font-weight: 500;
  cursor: pointer;
  transition: background-color 0.2s;
}

.primary-btn:hover, .retry-btn:hover {
  background-color: #1a252f;
}

@media (max-width: 768px) {
  .report-content {
    padding: 30px 20px;
  }
  
  .paper-title {
    font-size: 2.2rem;
  }
}
</style>
